// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { KialiArgs } from "./kiali";
export type Kiali = import("./kiali").Kiali;
export const Kiali: typeof import("./kiali").Kiali = null as any;
utilities.lazyLoad(exports, ["Kiali"], () => require("./kiali"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:kiali.io/v1alpha1:Kiali":
                return new Kiali(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "kiali.io/v1alpha1", _module)
