#!/usr/bin/env bash

secrets=$(\
  find manifests/1-manifest \( \
    -iname 'v1-secret*.yaml' -a \
    \! -iname 'bitnami.com_v1alpha1-sealedsecret*.yaml' \
  \)
)

[ -z "${secrets}" ] && exit 0

echo "${secrets}"

while IFS= read -r secret; do 
  newPath=${secret/v1-secret/bitnami.com_v1alpha1-sealedsecret}

  kubeseal \
    --controller-name=sealed-secrets \
    --controller-namespace=sealed-secrets-system \
    --format yaml \
    < ${secret} \
    > ${newPath}

done <<< "${secrets}"