// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./input";
import * as outputs from "./output";

import { ObjectMeta } from "../meta/v1";

export namespace kiali {
  export namespace v1alpha1 {}
}
