// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import {ObjectMeta} from "../meta/v1";

export namespace traefik {
    export namespace v1alpha1 {
        /**
         * IngressRouteSpec is a specification for a IngressRouteSpec resource.
         */
        export interface IngressRouteSpecArgs {
            entryPoints?: pulumi.Input<pulumi.Input<string>[]>;
            routes: pulumi.Input<pulumi.Input<inputs.traefik.v1alpha1.IngressRouteSpecRoutesArgs>[]>;
            /**
             * TLS contains the TLS certificates configuration of the routes. To enable Let's Encrypt, use an empty TLS struct, e.g. in YAML: 
             *  	 tls: {} # inline format 
             *  	 tls: 	   secretName: # block format
             */
            tls?: pulumi.Input<inputs.traefik.v1alpha1.IngressRouteSpecTlsArgs>;
        }

        /**
         * Route contains the set of routes.
         */
        export interface IngressRouteSpecRoutesArgs {
            kind: pulumi.Input<string>;
            match: pulumi.Input<string>;
            middlewares?: pulumi.Input<pulumi.Input<inputs.traefik.v1alpha1.IngressRouteSpecRoutesMiddlewaresArgs>[]>;
            priority?: pulumi.Input<number>;
            services?: pulumi.Input<pulumi.Input<inputs.traefik.v1alpha1.IngressRouteSpecRoutesServicesArgs>[]>;
        }

        /**
         * MiddlewareRef is a ref to the Middleware resources.
         */
        export interface IngressRouteSpecRoutesMiddlewaresArgs {
            name: pulumi.Input<string>;
            namespace?: pulumi.Input<string>;
        }

        /**
         * Service defines an upstream to proxy traffic.
         */
        export interface IngressRouteSpecRoutesServicesArgs {
            kind?: pulumi.Input<string>;
            /**
             * Name is a reference to a Kubernetes Service object (for a load-balancer of servers), or to a TraefikService object (service load-balancer, mirroring, etc). The differentiation between the two is specified in the Kind field.
             */
            name: pulumi.Input<string>;
            namespace?: pulumi.Input<string>;
            passHostHeader?: pulumi.Input<boolean>;
            port?: pulumi.Input<number | string>;
            /**
             * ResponseForwarding holds configuration for the forward of the response.
             */
            responseForwarding?: pulumi.Input<inputs.traefik.v1alpha1.IngressRouteSpecRoutesServicesResponseforwardingArgs>;
            scheme?: pulumi.Input<string>;
            serversTransport?: pulumi.Input<string>;
            /**
             * Sticky holds the sticky configuration.
             */
            sticky?: pulumi.Input<inputs.traefik.v1alpha1.IngressRouteSpecRoutesServicesStickyArgs>;
            strategy?: pulumi.Input<string>;
            /**
             * Weight should only be specified when Name references a TraefikService object (and to be precise, one that embeds a Weighted Round Robin).
             */
            weight?: pulumi.Input<number>;
        }

        /**
         * ResponseForwarding holds configuration for the forward of the response.
         */
        export interface IngressRouteSpecRoutesServicesResponseforwardingArgs {
            flushInterval?: pulumi.Input<string>;
        }

        /**
         * Sticky holds the sticky configuration.
         */
        export interface IngressRouteSpecRoutesServicesStickyArgs {
            /**
             * Cookie holds the sticky configuration based on cookie.
             */
            cookie?: pulumi.Input<inputs.traefik.v1alpha1.IngressRouteSpecRoutesServicesStickyCookieArgs>;
        }

        /**
         * Cookie holds the sticky configuration based on cookie.
         */
        export interface IngressRouteSpecRoutesServicesStickyCookieArgs {
            httpOnly?: pulumi.Input<boolean>;
            name?: pulumi.Input<string>;
            sameSite?: pulumi.Input<string>;
            secure?: pulumi.Input<boolean>;
        }

        /**
         * TLS contains the TLS certificates configuration of the routes. To enable Let's Encrypt, use an empty TLS struct, e.g. in YAML: 
         *  	 tls: {} # inline format 
         *  	 tls: 	   secretName: # block format
         */
        export interface IngressRouteSpecTlsArgs {
            certResolver?: pulumi.Input<string>;
            domains?: pulumi.Input<pulumi.Input<inputs.traefik.v1alpha1.IngressRouteSpecTlsDomainsArgs>[]>;
            /**
             * Options is a reference to a TLSOption, that specifies the parameters of the TLS connection.
             */
            options?: pulumi.Input<inputs.traefik.v1alpha1.IngressRouteSpecTlsOptionsArgs>;
            /**
             * SecretName is the name of the referenced Kubernetes Secret to specify the certificate details.
             */
            secretName?: pulumi.Input<string>;
            /**
             * Store is a reference to a TLSStore, that specifies the parameters of the TLS store.
             */
            store?: pulumi.Input<inputs.traefik.v1alpha1.IngressRouteSpecTlsStoreArgs>;
        }

        /**
         * Domain holds a domain name with SANs.
         */
        export interface IngressRouteSpecTlsDomainsArgs {
            main?: pulumi.Input<string>;
            sans?: pulumi.Input<pulumi.Input<string>[]>;
        }

        /**
         * Options is a reference to a TLSOption, that specifies the parameters of the TLS connection.
         */
        export interface IngressRouteSpecTlsOptionsArgs {
            name: pulumi.Input<string>;
            namespace?: pulumi.Input<string>;
        }

        /**
         * Store is a reference to a TLSStore, that specifies the parameters of the TLS store.
         */
        export interface IngressRouteSpecTlsStoreArgs {
            name: pulumi.Input<string>;
            namespace?: pulumi.Input<string>;
        }

        /**
         * MiddlewareSpec holds the Middleware configuration.
         */
        export interface MiddlewareSpecArgs {
            /**
             * AddPrefix holds the AddPrefix configuration.
             */
            addPrefix?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecAddprefixArgs>;
            /**
             * BasicAuth holds the HTTP basic authentication configuration.
             */
            basicAuth?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecBasicauthArgs>;
            /**
             * Buffering holds the request/response buffering configuration.
             */
            buffering?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecBufferingArgs>;
            /**
             * Chain holds a chain of middlewares.
             */
            chain?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecChainArgs>;
            /**
             * CircuitBreaker holds the circuit breaker configuration.
             */
            circuitBreaker?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecCircuitbreakerArgs>;
            /**
             * Compress holds the compress configuration.
             */
            compress?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecCompressArgs>;
            /**
             * ContentType middleware - or rather its unique `autoDetect` option - specifies whether to let the `Content-Type` header, if it has not been set by the backend, be automatically set to a value derived from the contents of the response. As a proxy, the default behavior should be to leave the header alone, regardless of what the backend did with it. However, the historic default was to always auto-detect and set the header if it was nil, and it is going to be kept that way in order to support users currently relying on it. This middleware exists to enable the correct behavior until at least the default one can be changed in a future version.
             */
            contentType?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecContenttypeArgs>;
            /**
             * DigestAuth holds the Digest HTTP authentication configuration.
             */
            digestAuth?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecDigestauthArgs>;
            /**
             * ErrorPage holds the custom error page configuration.
             */
            errors?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecErrorsArgs>;
            /**
             * ForwardAuth holds the http forward authentication configuration.
             */
            forwardAuth?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecForwardauthArgs>;
            /**
             * Headers holds the custom header configuration.
             */
            headers?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecHeadersArgs>;
            /**
             * InFlightReq limits the number of requests being processed and served concurrently.
             */
            inFlightReq?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecInflightreqArgs>;
            /**
             * IPWhiteList holds the ip white list configuration.
             */
            ipWhiteList?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecIpwhitelistArgs>;
            /**
             * PassTLSClientCert holds the TLS client cert headers configuration.
             */
            passTLSClientCert?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecPasstlsclientcertArgs>;
            plugin?: pulumi.Input<{[key: string]: pulumi.Input<{[key: string]: any}>}>;
            /**
             * RateLimit holds the rate limiting configuration for a given router.
             */
            rateLimit?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecRatelimitArgs>;
            /**
             * RedirectRegex holds the redirection configuration.
             */
            redirectRegex?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecRedirectregexArgs>;
            /**
             * RedirectScheme holds the scheme redirection configuration.
             */
            redirectScheme?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecRedirectschemeArgs>;
            /**
             * ReplacePath holds the ReplacePath configuration.
             */
            replacePath?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecReplacepathArgs>;
            /**
             * ReplacePathRegex holds the ReplacePathRegex configuration.
             */
            replacePathRegex?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecReplacepathregexArgs>;
            /**
             * Retry holds the retry configuration.
             */
            retry?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecRetryArgs>;
            /**
             * StripPrefix holds the StripPrefix configuration.
             */
            stripPrefix?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecStripprefixArgs>;
            /**
             * StripPrefixRegex holds the StripPrefixRegex configuration.
             */
            stripPrefixRegex?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecStripprefixregexArgs>;
        }

        /**
         * AddPrefix holds the AddPrefix configuration.
         */
        export interface MiddlewareSpecAddprefixArgs {
            prefix?: pulumi.Input<string>;
        }

        /**
         * BasicAuth holds the HTTP basic authentication configuration.
         */
        export interface MiddlewareSpecBasicauthArgs {
            headerField?: pulumi.Input<string>;
            realm?: pulumi.Input<string>;
            removeHeader?: pulumi.Input<boolean>;
            secret?: pulumi.Input<string>;
        }

        /**
         * Buffering holds the request/response buffering configuration.
         */
        export interface MiddlewareSpecBufferingArgs {
            maxRequestBodyBytes?: pulumi.Input<number>;
            maxResponseBodyBytes?: pulumi.Input<number>;
            memRequestBodyBytes?: pulumi.Input<number>;
            memResponseBodyBytes?: pulumi.Input<number>;
            retryExpression?: pulumi.Input<string>;
        }

        /**
         * Chain holds a chain of middlewares.
         */
        export interface MiddlewareSpecChainArgs {
            middlewares?: pulumi.Input<pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecChainMiddlewaresArgs>[]>;
        }

        /**
         * MiddlewareRef is a ref to the Middleware resources.
         */
        export interface MiddlewareSpecChainMiddlewaresArgs {
            name: pulumi.Input<string>;
            namespace?: pulumi.Input<string>;
        }

        /**
         * CircuitBreaker holds the circuit breaker configuration.
         */
        export interface MiddlewareSpecCircuitbreakerArgs {
            expression?: pulumi.Input<string>;
        }

        /**
         * Compress holds the compress configuration.
         */
        export interface MiddlewareSpecCompressArgs {
            excludedContentTypes?: pulumi.Input<pulumi.Input<string>[]>;
            minResponseBodyBytes?: pulumi.Input<number>;
        }

        /**
         * ContentType middleware - or rather its unique `autoDetect` option - specifies whether to let the `Content-Type` header, if it has not been set by the backend, be automatically set to a value derived from the contents of the response. As a proxy, the default behavior should be to leave the header alone, regardless of what the backend did with it. However, the historic default was to always auto-detect and set the header if it was nil, and it is going to be kept that way in order to support users currently relying on it. This middleware exists to enable the correct behavior until at least the default one can be changed in a future version.
         */
        export interface MiddlewareSpecContenttypeArgs {
            autoDetect?: pulumi.Input<boolean>;
        }

        /**
         * DigestAuth holds the Digest HTTP authentication configuration.
         */
        export interface MiddlewareSpecDigestauthArgs {
            headerField?: pulumi.Input<string>;
            realm?: pulumi.Input<string>;
            removeHeader?: pulumi.Input<boolean>;
            secret?: pulumi.Input<string>;
        }

        /**
         * ErrorPage holds the custom error page configuration.
         */
        export interface MiddlewareSpecErrorsArgs {
            query?: pulumi.Input<string>;
            /**
             * Service defines an upstream to proxy traffic.
             */
            service?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecErrorsServiceArgs>;
            status?: pulumi.Input<pulumi.Input<string>[]>;
        }

        /**
         * Service defines an upstream to proxy traffic.
         */
        export interface MiddlewareSpecErrorsServiceArgs {
            kind?: pulumi.Input<string>;
            /**
             * Name is a reference to a Kubernetes Service object (for a load-balancer of servers), or to a TraefikService object (service load-balancer, mirroring, etc). The differentiation between the two is specified in the Kind field.
             */
            name: pulumi.Input<string>;
            namespace?: pulumi.Input<string>;
            passHostHeader?: pulumi.Input<boolean>;
            port?: pulumi.Input<number | string>;
            /**
             * ResponseForwarding holds configuration for the forward of the response.
             */
            responseForwarding?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecErrorsServiceResponseforwardingArgs>;
            scheme?: pulumi.Input<string>;
            serversTransport?: pulumi.Input<string>;
            /**
             * Sticky holds the sticky configuration.
             */
            sticky?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecErrorsServiceStickyArgs>;
            strategy?: pulumi.Input<string>;
            /**
             * Weight should only be specified when Name references a TraefikService object (and to be precise, one that embeds a Weighted Round Robin).
             */
            weight?: pulumi.Input<number>;
        }

        /**
         * ResponseForwarding holds configuration for the forward of the response.
         */
        export interface MiddlewareSpecErrorsServiceResponseforwardingArgs {
            flushInterval?: pulumi.Input<string>;
        }

        /**
         * Sticky holds the sticky configuration.
         */
        export interface MiddlewareSpecErrorsServiceStickyArgs {
            /**
             * Cookie holds the sticky configuration based on cookie.
             */
            cookie?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecErrorsServiceStickyCookieArgs>;
        }

        /**
         * Cookie holds the sticky configuration based on cookie.
         */
        export interface MiddlewareSpecErrorsServiceStickyCookieArgs {
            httpOnly?: pulumi.Input<boolean>;
            name?: pulumi.Input<string>;
            sameSite?: pulumi.Input<string>;
            secure?: pulumi.Input<boolean>;
        }

        /**
         * ForwardAuth holds the http forward authentication configuration.
         */
        export interface MiddlewareSpecForwardauthArgs {
            address?: pulumi.Input<string>;
            authRequestHeaders?: pulumi.Input<pulumi.Input<string>[]>;
            authResponseHeaders?: pulumi.Input<pulumi.Input<string>[]>;
            authResponseHeadersRegex?: pulumi.Input<string>;
            /**
             * ClientTLS holds TLS specific configurations as client.
             */
            tls?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecForwardauthTlsArgs>;
            trustForwardHeader?: pulumi.Input<boolean>;
        }

        /**
         * ClientTLS holds TLS specific configurations as client.
         */
        export interface MiddlewareSpecForwardauthTlsArgs {
            caOptional?: pulumi.Input<boolean>;
            caSecret?: pulumi.Input<string>;
            certSecret?: pulumi.Input<string>;
            insecureSkipVerify?: pulumi.Input<boolean>;
        }

        /**
         * Headers holds the custom header configuration.
         */
        export interface MiddlewareSpecHeadersArgs {
            /**
             * AccessControlAllowCredentials is only valid if true. false is ignored.
             */
            accessControlAllowCredentials?: pulumi.Input<boolean>;
            /**
             * AccessControlAllowHeaders must be used in response to a preflight request with Access-Control-Request-Headers set.
             */
            accessControlAllowHeaders?: pulumi.Input<pulumi.Input<string>[]>;
            /**
             * AccessControlAllowMethods must be used in response to a preflight request with Access-Control-Request-Method set.
             */
            accessControlAllowMethods?: pulumi.Input<pulumi.Input<string>[]>;
            /**
             * AccessControlAllowOriginList is a list of allowable origins. Can also be a wildcard origin "*".
             */
            accessControlAllowOriginList?: pulumi.Input<pulumi.Input<string>[]>;
            /**
             * AccessControlAllowOriginListRegex is a list of allowable origins written following the Regular Expression syntax (https://golang.org/pkg/regexp/).
             */
            accessControlAllowOriginListRegex?: pulumi.Input<pulumi.Input<string>[]>;
            /**
             * AccessControlExposeHeaders sets valid headers for the response.
             */
            accessControlExposeHeaders?: pulumi.Input<pulumi.Input<string>[]>;
            /**
             * AccessControlMaxAge sets the time that a preflight request may be cached.
             */
            accessControlMaxAge?: pulumi.Input<number>;
            /**
             * AddVaryHeader controls if the Vary header is automatically added/updated when the AccessControlAllowOriginList is set.
             */
            addVaryHeader?: pulumi.Input<boolean>;
            allowedHosts?: pulumi.Input<pulumi.Input<string>[]>;
            browserXssFilter?: pulumi.Input<boolean>;
            contentSecurityPolicy?: pulumi.Input<string>;
            contentTypeNosniff?: pulumi.Input<boolean>;
            customBrowserXSSValue?: pulumi.Input<string>;
            customFrameOptionsValue?: pulumi.Input<string>;
            customRequestHeaders?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
            customResponseHeaders?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
            /**
             * Deprecated: use PermissionsPolicy instead.
             */
            featurePolicy?: pulumi.Input<string>;
            forceSTSHeader?: pulumi.Input<boolean>;
            frameDeny?: pulumi.Input<boolean>;
            hostsProxyHeaders?: pulumi.Input<pulumi.Input<string>[]>;
            isDevelopment?: pulumi.Input<boolean>;
            permissionsPolicy?: pulumi.Input<string>;
            publicKey?: pulumi.Input<string>;
            referrerPolicy?: pulumi.Input<string>;
            /**
             * Deprecated: use RedirectRegex instead.
             */
            sslForceHost?: pulumi.Input<boolean>;
            /**
             * Deprecated: use RedirectRegex instead.
             */
            sslHost?: pulumi.Input<string>;
            sslProxyHeaders?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
            /**
             * Deprecated: use EntryPoint redirection or RedirectScheme instead.
             */
            sslRedirect?: pulumi.Input<boolean>;
            /**
             * Deprecated: use EntryPoint redirection or RedirectScheme instead.
             */
            sslTemporaryRedirect?: pulumi.Input<boolean>;
            stsIncludeSubdomains?: pulumi.Input<boolean>;
            stsPreload?: pulumi.Input<boolean>;
            stsSeconds?: pulumi.Input<number>;
        }

        /**
         * InFlightReq limits the number of requests being processed and served concurrently.
         */
        export interface MiddlewareSpecInflightreqArgs {
            amount?: pulumi.Input<number>;
            /**
             * SourceCriterion defines what criterion is used to group requests as originating from a common source. If none are set, the default is to use the request's remote address field. All fields are mutually exclusive.
             */
            sourceCriterion?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecInflightreqSourcecriterionArgs>;
        }

        /**
         * SourceCriterion defines what criterion is used to group requests as originating from a common source. If none are set, the default is to use the request's remote address field. All fields are mutually exclusive.
         */
        export interface MiddlewareSpecInflightreqSourcecriterionArgs {
            /**
             * IPStrategy holds the ip strategy configuration.
             */
            ipStrategy?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecInflightreqSourcecriterionIpstrategyArgs>;
            requestHeaderName?: pulumi.Input<string>;
            requestHost?: pulumi.Input<boolean>;
        }

        /**
         * IPStrategy holds the ip strategy configuration.
         */
        export interface MiddlewareSpecInflightreqSourcecriterionIpstrategyArgs {
            depth?: pulumi.Input<number>;
            excludedIPs?: pulumi.Input<pulumi.Input<string>[]>;
        }

        /**
         * IPWhiteList holds the ip white list configuration.
         */
        export interface MiddlewareSpecIpwhitelistArgs {
            /**
             * IPStrategy holds the ip strategy configuration.
             */
            ipStrategy?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecIpwhitelistIpstrategyArgs>;
            sourceRange?: pulumi.Input<pulumi.Input<string>[]>;
        }

        /**
         * IPStrategy holds the ip strategy configuration.
         */
        export interface MiddlewareSpecIpwhitelistIpstrategyArgs {
            depth?: pulumi.Input<number>;
            excludedIPs?: pulumi.Input<pulumi.Input<string>[]>;
        }

        /**
         * PassTLSClientCert holds the TLS client cert headers configuration.
         */
        export interface MiddlewareSpecPasstlsclientcertArgs {
            /**
             * TLSClientCertificateInfo holds the client TLS certificate info configuration.
             */
            info?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecPasstlsclientcertInfoArgs>;
            pem?: pulumi.Input<boolean>;
        }

        /**
         * TLSClientCertificateInfo holds the client TLS certificate info configuration.
         */
        export interface MiddlewareSpecPasstlsclientcertInfoArgs {
            /**
             * TLSClientCertificateIssuerDNInfo holds the client TLS certificate distinguished name info configuration. cf https://tools.ietf.org/html/rfc3739
             */
            issuer?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecPasstlsclientcertInfoIssuerArgs>;
            notAfter?: pulumi.Input<boolean>;
            notBefore?: pulumi.Input<boolean>;
            sans?: pulumi.Input<boolean>;
            serialNumber?: pulumi.Input<boolean>;
            /**
             * TLSClientCertificateSubjectDNInfo holds the client TLS certificate distinguished name info configuration. cf https://tools.ietf.org/html/rfc3739
             */
            subject?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecPasstlsclientcertInfoSubjectArgs>;
        }

        /**
         * TLSClientCertificateIssuerDNInfo holds the client TLS certificate distinguished name info configuration. cf https://tools.ietf.org/html/rfc3739
         */
        export interface MiddlewareSpecPasstlsclientcertInfoIssuerArgs {
            commonName?: pulumi.Input<boolean>;
            country?: pulumi.Input<boolean>;
            domainComponent?: pulumi.Input<boolean>;
            locality?: pulumi.Input<boolean>;
            organization?: pulumi.Input<boolean>;
            province?: pulumi.Input<boolean>;
            serialNumber?: pulumi.Input<boolean>;
        }

        /**
         * TLSClientCertificateSubjectDNInfo holds the client TLS certificate distinguished name info configuration. cf https://tools.ietf.org/html/rfc3739
         */
        export interface MiddlewareSpecPasstlsclientcertInfoSubjectArgs {
            commonName?: pulumi.Input<boolean>;
            country?: pulumi.Input<boolean>;
            domainComponent?: pulumi.Input<boolean>;
            locality?: pulumi.Input<boolean>;
            organization?: pulumi.Input<boolean>;
            organizationalUnit?: pulumi.Input<boolean>;
            province?: pulumi.Input<boolean>;
            serialNumber?: pulumi.Input<boolean>;
        }

        /**
         * RateLimit holds the rate limiting configuration for a given router.
         */
        export interface MiddlewareSpecRatelimitArgs {
            average?: pulumi.Input<number>;
            burst?: pulumi.Input<number>;
            period?: pulumi.Input<number | string>;
            /**
             * SourceCriterion defines what criterion is used to group requests as originating from a common source. If none are set, the default is to use the request's remote address field. All fields are mutually exclusive.
             */
            sourceCriterion?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecRatelimitSourcecriterionArgs>;
        }

        /**
         * SourceCriterion defines what criterion is used to group requests as originating from a common source. If none are set, the default is to use the request's remote address field. All fields are mutually exclusive.
         */
        export interface MiddlewareSpecRatelimitSourcecriterionArgs {
            /**
             * IPStrategy holds the ip strategy configuration.
             */
            ipStrategy?: pulumi.Input<inputs.traefik.v1alpha1.MiddlewareSpecRatelimitSourcecriterionIpstrategyArgs>;
            requestHeaderName?: pulumi.Input<string>;
            requestHost?: pulumi.Input<boolean>;
        }

        /**
         * IPStrategy holds the ip strategy configuration.
         */
        export interface MiddlewareSpecRatelimitSourcecriterionIpstrategyArgs {
            depth?: pulumi.Input<number>;
            excludedIPs?: pulumi.Input<pulumi.Input<string>[]>;
        }

        /**
         * RedirectRegex holds the redirection configuration.
         */
        export interface MiddlewareSpecRedirectregexArgs {
            permanent?: pulumi.Input<boolean>;
            regex?: pulumi.Input<string>;
            replacement?: pulumi.Input<string>;
        }

        /**
         * RedirectScheme holds the scheme redirection configuration.
         */
        export interface MiddlewareSpecRedirectschemeArgs {
            permanent?: pulumi.Input<boolean>;
            port?: pulumi.Input<string>;
            scheme?: pulumi.Input<string>;
        }

        /**
         * ReplacePath holds the ReplacePath configuration.
         */
        export interface MiddlewareSpecReplacepathArgs {
            path?: pulumi.Input<string>;
        }

        /**
         * ReplacePathRegex holds the ReplacePathRegex configuration.
         */
        export interface MiddlewareSpecReplacepathregexArgs {
            regex?: pulumi.Input<string>;
            replacement?: pulumi.Input<string>;
        }

        /**
         * Retry holds the retry configuration.
         */
        export interface MiddlewareSpecRetryArgs {
            attempts?: pulumi.Input<number>;
            initialInterval?: pulumi.Input<number | string>;
        }

        /**
         * StripPrefix holds the StripPrefix configuration.
         */
        export interface MiddlewareSpecStripprefixArgs {
            forceSlash?: pulumi.Input<boolean>;
            prefixes?: pulumi.Input<pulumi.Input<string>[]>;
        }

        /**
         * StripPrefixRegex holds the StripPrefixRegex configuration.
         */
        export interface MiddlewareSpecStripprefixregexArgs {
            regex?: pulumi.Input<pulumi.Input<string>[]>;
        }
    }
}
